# Generated by Django 6.0.2 on 2026-02-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="descripition",
            new_name="description",
        ),
    ]
